export const data = [
    {
      id: 1,
      firstName: 'John',
      lastName: 'Doe',
      avatar: 'https://example.com/avatar1.png',
      email: 'john.doe@example.com',
      salary: 50000,
      jobTitle: 'Software Engineer',
      startDate: '2022-01-01',
      signatureCatchPhrase: 'Hello World!',
    },
    {
      id: 2,
      firstName: 'Jane',
      lastName: 'Smith',
      avatar: 'https://example.com/avatar2.png',
      email: 'jane.smith@example.com',
      salary: 75000,
      jobTitle: 'Product Manager',
      startDate: '',
      signatureCatchPhrase: 'Work hard, play hard!',
    },
    {
        id: 2,
        firstName: 'Jane',
        lastName: 'Smith',
        avatar: 'https://example.com/avatar2.png',
        email: 'jane.smith@example.com',
        salary: 75000,
        jobTitle: 'Product Manager',
        startDate: '',
        signatureCatchPhrase: 'Work hard, play hard!',
      },
      {
        id: 2,
        firstName: 'Jane',
        lastName: 'Smith',
        avatar: 'https://example.com/avatar2.png',
        email: 'jane.smith@example.com',
        salary: 75000,
        jobTitle: 'Product Manager',
        startDate: '',
        signatureCatchPhrase: 'Work hard, play hard!',
      },
      {
        id: 2,
        firstName: 'Jane',
        lastName: 'Smith',
        avatar: 'https://example.com/avatar2.png',
        email: 'jane.smith@example.com',
        salary: 75000,
        jobTitle: 'Product Manager',
        startDate: '',
        signatureCatchPhrase: 'Work hard, play hard!',
      },
      {
        id: 2,
        firstName: 'Jane',
        lastName: 'Smith',
        avatar: 'https://example.com/avatar2.png',
        email: 'jane.smith@example.com',
        salary: 75000,
        jobTitle: 'Product Manager',
        startDate: '',
        signatureCatchPhrase: 'Work hard, play hard!',
      },
      {
        id: 2,
        firstName: 'Jane',
        lastName: 'Smith',
        avatar: 'https://example.com/avatar2.png',
        email: 'jane.smith@example.com',
        salary: 75000,
        jobTitle: 'Product Manager',
        startDate: '',
        signatureCatchPhrase: 'Work hard, play hard!',
      },
      {
        id: 2,
        firstName: 'Jane',
        lastName: 'Smith',
        avatar: 'https://example.com/avatar2.png',
        email: 'jane.smith@example.com',
        salary: 75000,
        jobTitle: 'Product Manager',
        startDate: '',
        signatureCatchPhrase: 'Work hard, play hard!',
      },
      {
        id: 2,
        firstName: 'Jane',
        lastName: 'Smith',
        avatar: 'https://example.com/avatar2.png',
        email: 'jane.smith@example.com',
        salary: 75000,
        jobTitle: 'Product Manager',
        startDate: '',
        signatureCatchPhrase: 'Work hard, play hard!',
      },
      {
        id: 2,
        firstName: 'Jane',
        lastName: 'Smith',
        avatar: 'https://example.com/avatar2.png',
        email: 'jane.smith@example.com',
        salary: 75000,
        jobTitle: 'Product Manager',
        startDate: '',
        signatureCatchPhrase: 'Work hard, play hard!',
      },
      {
        id: 2,
        firstName: 'Jane',
        lastName: 'Smith',
        avatar: 'https://example.com/avatar2.png',
        email: 'jane.smith@example.com',
        salary: 75000,
        jobTitle: 'Product Manager',
        startDate: '',
        signatureCatchPhrase: 'Work hard, play hard!',
      },
      {
        id: 2,
        firstName: 'Jane',
        lastName: 'Smith',
        avatar: 'https://example.com/avatar2.png',
        email: 'jane.smith@example.com',
        salary: 75000,
        jobTitle: 'Product Manager',
        startDate: '',
        signatureCatchPhrase: 'Work hard, play hard!',
      },
      {
        id: 2,
        firstName: 'Jane',
        lastName: 'Smith',
        avatar: 'https://example.com/avatar2.png',
        email: 'jane.smith@example.com',
        salary: 75000,
        jobTitle: 'Product Manager',
        startDate: '',
        signatureCatchPhrase: 'Work hard, play hard!',
      },
      {
        id: 2,
        firstName: 'Jane',
        lastName: 'Smith',
        avatar: 'https://example.com/avatar2.png',
        email: 'jane.smith@example.com',
        salary: 75000,
        jobTitle: 'Product Manager',
        startDate: '',
        signatureCatchPhrase: 'Work hard, play hard!',
      },
      {
        id: 2,
        firstName: 'Jane',
        lastName: 'Smith',
        avatar: 'https://example.com/avatar2.png',
        email: 'jane.smith@example.com',
        salary: 75000,
        jobTitle: 'Product Manager',
        startDate: '',
        signatureCatchPhrase: 'Work hard, play hard!',
      },  {
        id: 2,
        firstName: 'Jane',
        lastName: 'Smith',
        avatar: 'https://example.com/avatar2.png',
        email: 'jane.smith@example.com',
        salary: 75000,
        jobTitle: 'Product Manager',
        startDate: '',
        signatureCatchPhrase: 'Work hard, play hard!',
      },
      {
        id: 2,
        firstName: 'Jane',
        lastName: 'Smith',
        avatar: 'https://example.com/avatar2.png',
        email: 'jane.smith@example.com',
        salary: 75000,
        jobTitle: 'Product Manager',
        startDate: '',
        signatureCatchPhrase: 'Work hard, play hard!',
      },
      {
        id: 2,
        firstName: 'Jane',
        lastName: 'Smith',
        avatar: 'https://example.com/avatar2.png',
        email: 'jane.smith@example.com',
        salary: 75000,
        jobTitle: 'Product Manager',
        startDate: '',
        signatureCatchPhrase: 'Work hard, play hard!',
      },
      {
        id: 2,
        firstName: 'Jane',
        lastName: 'Smith',
        avatar: 'https://example.com/avatar2.png',
        email: 'jane.smith@example.com',
        salary: 75000,
        jobTitle: 'Product Manager',
        startDate: '',
        signatureCatchPhrase: 'Work hard, play hard!',
      },
      {
        id: 2,
        firstName: 'Jane',
        lastName: 'Smith',
        avatar: 'https://example.com/avatar2.png',
        email: 'jane.smith@example.com',
        salary: 75000,
        jobTitle: 'Product Manager',
        startDate: '',
        signatureCatchPhrase: 'Work hard, play hard!',
      },
    // Add more objects for additional rows
  ];